### ISSUE TITLE
Redux の見出しだけ「どういう事に向いてる?」になっている

### ISSUE THREAD

**Issue by stak** [azu/JavaScript-Plugin-Architecture#114]
> どういう用途に向いている?
> どういう用途に向いていない?

が全体的なフォーマットだと思うのですが、Redux のページのみ

> どういう事に向いてる?
> どういう事に向いていない?

となっています。
何か意図があるかもしれないと思い Issue にて。

**Comment by azu** [comment]
2821de4 で修正しました。
原因としては[CONTRIBUTING.md](https://github.com/azu/JavaScript-Plugin-Architecture/blob/master/CONTRIBUTING.md "CONTRIBUTING.md")自体に"い"の抜けがあって、それをコピペしたからですね。

**Comment by stak** [comment]
> 事

と

> 用途

という揺れもあるのですが、問題ないでしょうか。

**Comment by azu** [comment]
ありがとうございます。合わせて修正しました。
