### ISSUE TITLE
「前提の解決」とは？

### ISSUE THREAD

**Issue by orangain** [azu/JavaScript-Plugin-Architecture#121]
[Connectの「どういう用途に向いていない」](https://github.com/azu/JavaScript-Plugin-Architecture/blob/884df1f9019c591740b2ccd8cabe4e868ac3137e/ja/connect/README.md#どういう用途に向いていない)に以下の文がありますが、「前提の解決」の意味はなんとなくわかりますが、表現が適切でないように思います。

> この場合、use(middleware) で登録する順番により挙動が変わります。 middleware の利用者が、間で起きる前提の解決を行う必要があります。

あまり良い直し方が思いつきませんが、「依存関係の解決」や「依存関係の問題を解決する必要が〜」などでしょうか。

**Comment by azu** [comment]
依存関係の解決 的な事を書きたかったのかと思います。

**Comment by azu** [comment]
> _middleware_ の利用者が、middleware間の依存関係を解決する必要があります。
