### ISSUE TITLE
書籍のタイトル/ハッシュタグ

### ISSUE THREAD

**Issue by azu** [azu/JavaScript-Plugin-Architecture#66]
_JavaScript Plugin Architecture_ というタイトルにとりあえずしているけど、まだ決定という感じではない。
もっと適切なものを募集しています。

タイトルと合わせてハッシュタグ or 略称が欲しい。(このタイトル略しにくい)

**Comment by twada** [comment]
とりあえず凡庸なところから挙げてみます

- \#js_plugin_book
- \#js_plugin_architecture

**Comment by azu** [comment]
#58 が終わったら一区切り的な意味合いで1.0としてリリースする予定。
タイトルはそのままでいいとして、ハッシュタグは #js_plugin_book にしますかー
