### ISSUE TITLE
リリース方針

### ISSUE THREAD

**Issue by azu** [azu/JavaScript-Plugin-Architecture#67]
この書籍をリリース(公開はされてるけど)するときに、色々ちゃんとしないと見てもらうのは難しいので、その辺の整理をするIssueです。

- [x] タイトル決める #66 - JavaScript Plugin Architecture
- [x] GitHub Pages or GitBook.com ?
     - PDF/epubのビルドが面倒な以外はGitHub pagesでも問題ない
     - 連携だけしておいて、gitbook.comのpdf/epubへのリンクを付けるという手もある…(gitbookには悪いけど)
- [x] README.mdとIntroductionの役割を分離 #36 
     - README.mdはgitbook上にでるので、Landing Page的な扱い
     - この書籍の読み方みたいのもないと多分読めない気がする
     - 各章の簡単な概要をまとめると読み始めやすいのでは
- [x] Landing Pageの見た目
     - Landing Pageは https://azu.gitbooks.io/javascript-plugin-architecture/ でアクセスできるんだけど、/details にリダイレクトされるのが気に入らない…
- [x] GitBookからGitHubリポジトリへのリンクが欲しい(あるけど分かりづらい)
- [x] はてブボタン
- [x] Donationボタン? (GitBookにはデフォルトでGumroadを使ったDonationがあった)
- [x] Analytics

この書籍は対象が特殊な感じがするし、基本的には章は独立してるからバラバラに読めるけど、
そういう読み方とかどこから来た人が読むのかみたいのの意識は必要そう。

ある種のデザインパターン本という感じだけど、読みやすいデザインパターン本の構成ってどんなのだろ?

**Comment by azu** [comment]
Landing Pageとしては、このリポジトリを使うようにした。
ここがベースでgitbook.comはフォーマットの置き場だよって感じ。

**Comment by azu** [comment]
[Release 1.0.0 · azu/JavaScript-Plugin-Architecture](https://github.com/azu/JavaScript-Plugin-Architecture/releases/tag/1.0.0 "Release 1.0.0 · azu/JavaScript-Plugin-Architecture")

リリース 🎉

**Comment by twada** [comment]
🎉
